### ISSUE TITLE
Macos - sudo make install linker error

### ISSUE THREAD

**Issue by loewal** [szpajder/dumphfdl#15]
Hi,

This is my output of cmake..
Checking for module 'libacars-2>=2.1.0'
--   Found libacars-2, version 2.1.3
-- Checking for module 'libconfig++'
--   Found libconfig++, version 1.7.3
-- Checking for SoapySDR
--   SoapySDR found, /usr/local/include, SoapySDR
-- Found SQLite3: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include (found version "3.36.0")
-- Checking for module 'libzmq>=3.2.0'
--   Found libzmq, version 4.3.4
-- dumphfdl configuration summary:
-- - SDR drivers:
--   - soapysdr:		requested: ON, enabled: TRUE
-- - Other options:
--   - Etsy StatsD:		requested: ON, enabled: FALSE
--   - SQLite:			requested: ON, enabled: TRUE
--   - ZeroMQ:			requested: ON, enabled: TRUE
--   - Profiling:		requested: OFF, enabled: FALSE
--   - Multithreaded FFT:	TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/Loewal/Downloads/dumphfdl/build

Output of make:
[100%] Linking C executable dumphfdl
[100%] Built target dumphfdl

Output of sudo make install:
[ 97%] Built target fec
[100%] Linking C executable dumphfdl
ld: library not found for -lacars-2
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/dumphfdl] Error 1
make[1]: *** [src/CMakeFiles/dumphfdl.dir/all] Error 2

Ain't this strange?

**Comment by szpajder** [comment]
I don't have a Mac at hand, however there is a Github workflow for this project which builds it on MacOS 11 and 10.15 and it does work (https://github.com/szpajder/dumphfdl/blob/master/.github/workflows/build.yml). Basically what it does is (slightly edited for readability):

```
brew update
brew install liquid-dsp fftw soapysdr libconfig

# Install libacars
git clone https://github.com/szpajder/libacars.git
cd libacars
mkdir build
cd build
cmake ..
make
sudo make install
sudo update_dyld_shared_cache

# Build dumphfdl
git clone https://github.com/szpajder/dumphfdl.git
cd dumphfdl
mkdir build
cd build
cmake ../
make
```

So can you please initially do `sudo update_dyld_shared_cache` and then again `make` to see if it's any better?

Otherwise please describe how is your build process different compared to the above workflow (which apparently works, at least in Github's testing environment).

**Comment by loewal** [comment]
Hi,
Thanks for the quick reply!

I deleted all my stuff and compiled again.

The command "sudo update_dyld_shared_cache” gives “this command is deprecated”…..

All went well, but after “make” I issued “sudo make install” and then...

~/Downloads/dumphfdl/build/ sudo make install
Consolidate compiler generated dependencies of target dumphfdl_base
[ 2%] Generating version.c, _version.c
[ 4%] Building C object src/CMakeFiles/dumphfdl_base.dir/version.c.o
[ 95%] Built target dumphfdl_base
Consolidate compiler generated dependencies of target fec
[ 97%] Built target fec
[100%] Linking C executable dumphfdl
ld: library not found for -lacars-2
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/dumphfdl] Error 1
make[1]: *** [src/CMakeFiles/dumphfdl.dir/all] Error 2
make: *** [all] Error 2

Thnx

**Comment by szpajder** [comment]
So has libacars actually been installed correctly?

Does `ls -l /usr/local/lib/libacars*` show anything?

Can you run the example apps that come bundled and installed with libacars? Like `decode_acars_apps -h` - does it run at all?

Which MacOS version are you on?

**Comment by loewal** [comment]
Thanks again,

It appears that everything is installed correctly.
The last step doesn’t seem to be necessary (sudo make install) or isn’t allowed…?

Thank you!

**Comment by szpajder** [comment]
Ah, indeed! I missed that you've executed `make` which succeeded and it's only `sudo make install` which failed. Sorry about that.

However I'm a little puzzed on what might be the cause of this. `sudo` should just run the given command as root, in the current directory (which is `build`). This is required in order to copy the dumphfdl binary to /usr/local/bin, which is writable only by root. Alternatively, can you just `su` to root, go to the `build` directory and then do `make install`? Would it be any better?

**Comment by loewal** [comment]
I looked for dumphfdl and found it in /usr/local/bin.
Even stranger…?
But it’s working okay now.
I just wondered how you get that nice coloured output.
With “prettify-xml”?

**Comment by szpajder** [comment]
See here: https://github.com/szpajder/dumphfdl#i-want-colorized-logs-like-on-the-screenshot
